!function(t){var e={};function n(a){if(e[a])return e[a].exports;var i=e[a]={i:a,l:!1,exports:{}};return t[a].call(i.exports,i,i.exports,n),i.l=!0,i.exports}n.m=t,n.c=e,n.d=function(t,e,a){n.o(t,e)||Object.defineProperty(t,e,{enumerable:!0,get:a})},n.r=function(t){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(t,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(t,"__esModule",{value:!0})},n.t=function(t,e){if(1&e&&(t=n(t)),8&e)return t;if(4&e&&"object"==typeof t&&t&&t.__esModule)return t;var a=Object.create(null);if(n.r(a),Object.defineProperty(a,"default",{enumerable:!0,value:t}),2&e&&"string"!=typeof t)for(var i in t)n.d(a,i,function(e){return t[e]}.bind(null,i));return a},n.n=function(t){var e=t&&t.__esModule?function(){return t.default}:function(){return t};return n.d(e,"a",e),e},n.o=function(t,e){return Object.prototype.hasOwnProperty.call(t,e)},n.p="",n(n.s=1)}([,function(t,e,n){"use strict";n.r(e);n(2),n(3),n(4)},function(t,e,n){},function(t,e){jQuery(document).ready((function(t){t("#wpadminbar")[0]?(console.log("fix wpadminbar"),t(window).width()>480?(t(".top-header-bk-bar").css({top:"32px"}),t("#main-header-container").css({top:"72px"}),t("body").hasClass("home")||t("#content-area").css({"margin-top":"50px"})):(t("#wpadminbar").css("position","fixed"),t(".fixed-top").css({top:"45px"}),t("#main-menu-container, #top-search-container").css({"margin-top":"45px"}),t("body").hasClass("home")||t("#content-area").css({"margin-top":"50px"}))):t("body").hasClass("home")||t("#content-area").css({"margin-top":"50px"}),jQuery("body").on("click",".main-menu-btn",(function(){jQuery("body").toggleClass("showMenu")})),document.cookie.search(/\wordpress_logged_in-\S*=/)}))},function(t,e,n){var a=new(n(5))({});jQuery(document).ready((function(t){window.location.origin,window.location.pathname;var e=window.location.search.substring(1).split("&");e&&e.forEach((function(t,e){t.includes("page")&&parseInt(t.split("=")[1])}));var n=function(e){t(e).data("total-pages")<=t(e).data("paged")?t(e).find(".searchNextPage").hide():t(e).find(".searchNextPage").show()};n(t("#search-result-body")),t("a.searchNextPage").html('Load More <i class="fa fa-arrow-down" aria-hidden="true"></i>'),t("a.searchNextPage").click((function(e){var i=this,s=t(i).attr("href"),o=new XMLHttpRequest;t("a.searchNextPage").html('<span class="spinner-grow spinner-grow-sm" role="status" aria-hidden="true"></span>Loading...'),t.ajax(s,{xhr:function(){return o},success:function(e,s,r){var h=t(e).find(".searchNextPage").attr("href"),c=t(e).find("#search-results").html();t(e).find("#search-result-body").data("paged"),t("#search-results").append(c),a.push(o.responseURL),t(e).find(".searchNextPage").length&&(t(i).attr("href",h),t("a.searchNextPage").html('Load More <i class="fa fa-arrow-down" aria-hidden="true"></i>')),n(t("#search-result-body"))}}),e.preventDefault()}))}))},function(t,e,n){
/*!
 *
 * Handles history pushstate/popstate with async option
 * If history is not supported, falls back to hashbang!
 *
 * @PushState
 * @author: kitajchuk
 *
 */
var a;t.exports=((a=function(){return this.init.apply(this,arguments)}).prototype={constructor:a,_pushable:"history"in window&&"pushState"in window.history,_hashable:"onhashchange"in window,init:function(t){this._initUrl=window.location.href.replace(window.location.hash,""),this._options=t||{},this._enabled=!1,this._ishashpushed=!1,this._uid=0,this._states={},this._callbacks={},this._states[this._initUrl]={uid:this.getUID()},this._stateEnable()},on:function(t,e){"function"==typeof e&&(this._callbacks[t]||(this._callbacks[t]=[]),e._pushstateID=this.getUID(),e._pushstateType=t,this._callbacks[t].push(e))},off:function(t,e){if(this._callbacks[t])for(var n=this._callbacks[t].length;n--;)if(this._callbacks[t][n]._pushstateID===e._pushstateID){this._callbacks[t].splice(n,1);break}},push:function(t){t!==window.location.href&&(this._push(t),this._states[t]={uid:this.getUID()})},goBack:function(){window.history.back(),this._fire("backstate")},goForward:function(){window.history.forward(),this._fire("forwardstate")},getUID:function(){return this._uid=this._uid+1,this._uid},_push:function(t){if(this._pushable&&!this._options.forceHash)window.history.pushState(this._states[t],"",t);else{var e=t.replace(window.location.origin,"");e===window.location.pathname&&(e="/"),this._ishashpushed=!0,window.location.hash=e}},_fire:function(t,e){if(this._callbacks[t])for(var n=this._callbacks[t].length;n--;)this._callbacks[t][n].apply(this,[].slice.call(arguments,1))},_stateEnable:function(){if(this._enabled)return this;var t=this,e=function(){var e=window.location.href;t._options.forceHash&&(e=(e=e.replace(window.location.hash,"")).replace(window.location.pathname,""),-1!==["#/","#",""].indexOf(window.location.hash)?e+=window.location.pathname:e+=window.location.hash.replace("#","")),t._fire("popstate",e,t._states[e])};this._enabled=!0,this._pushable&&!this._options.forceHash?window.addEventListener("popstate",(function(t){e()}),!1):this._hashable&&(this._push(this._initUrl),window.addEventListener("hashchange",(function(n){t._ishashpushed?t._ishashpushed=!1:e()}),!1))}},a)}]);
//# sourceMappingURL=index.js.map